resilience4j:
  circuitbreaker:
    intances:
      productCB:
        slidingWindowType: TIME_BASED
        slidingWindowSize: '10'
        failureRateThreshold: '50'
        permittedNumberOfCallsInHalfOpenState: '3'
        waitDurationInOpenState: 5s
        eventConsumerBufferSize: '10'
        registerHealthIndicator: 'true'
        minimumNumberOfCalls: '4'
      userCB:
        registerHealthIndicator: 'true'
        eventConsumerBufferSize: '10'
        failureRateThreshold: '50'
        minimumNumberOfCalls: '4'
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '10'
        waitDurationInOpenState: 5s
        slidingWindowType: TIME_BASED
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Buele30.03.1997LES
    username: postgres
    url: jdbc:postgresql://db.ssnqugygamsjojwjqqjj.supabase.co/postgres
server:
  error:
    include-binding-erros: always
    include-message: always
  port: ${port:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: http://52.73.98.2:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        incluse: '"*"'
logging:
  pattern:
    console: '"%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"'