server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://52.73.98.2:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: aliments-service
          uri: lb://aliments-service
          predicates:
            - Path=/alimentation/**
        - id: pill-service
          uri: lb://pill-service
          predicates:
            - Path=/pills/**
        - id: tratamientos-service
          uri: lb://tratamientos-service
          predicates:
            - Path=/treatement/**
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/fridge/**
        - id: actividadfisica-service
          uri: lb://actividadfisica-service
          predicates:
            - Path=/activity/**
        - id: control-service
          uri: lb://control-service
          predicates:
            - Path=/control/**
        - id: measure-service
          uri: lb://measure-service
          predicates:
            - Path=/measures/**
