server:
  error:
    include-binding-errors: always
    include-message: always
  port: '8091'
spring:
  data:
    mongodb:
      database: Registers
      uri: mongodb+srv://aracely10:aracely1008@cluster0.biago.mongodb.net/?retryWrites=true&w=majority
    application:
      name: measure-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://52.73.98.2:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"