
eureka:
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
    serviceUrl:
      defaultZone: http://52.73.98.2:8099/eureka/
spring:
  application:
    name: PillService
  data:
    mongodb:
      uri: mongodb+srv://danielseaman:betelgeuse@cluster0.0pwrpay.mongodb.net/smartdrugsdb?retryWrites=true&w=majority
server:
  port: '8084'
  servlet:
    application-display-name: PillService
